<?php

/**
 * Created by PhpStorm.
 * User: byd
 * Date: 16/6/12
 * Time: 下午2:52
 */
class ShareController extends ApiController
{
    public function init()
    {
        $this->out_arr = $this->out_arr();
        $this->db = DbUtils::createDbUtils(true);
        //parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 分享列表
     */
    public function actionShareList()
    {
        (int)$page = isset($this->data['page']) ? $this->data['page'] : 1;
        $pageSize = 10;
        $str = ($page - 1) * $pageSize;
        $sql = 'SELECT id,name,count,starttime,endtime FROM %t LiMIT %d,%d';
        $data['items'] = $this->db->queryAll($sql, array('appbyme_share', $str, $pageSize));
        $count = $this->db->queryRow("SELECT count(id) AS total_items FROM %t", array('appbyme_share'));
        $data['total_items'] = $count['total_items'];//共多少条数据
        $data['current'] = $page;//现在在第几页
        $data['total_pages'] = ceil($count['total_items'] / $pageSize);//计算共几页
        if ($page != 1) {
            $data['before'] = $page - 1;//上一页
        }
        if ($page != $data['total_pages']) {
            $data['next'] = $page + 1;//下一页
        }
        $data['limit'] = $pageSize;//每页展示数据条数
        $this->setData($data);
    }

    /**
     * 分享添加/编辑操作
     */
    public function actionShareAdd()
    {
        $id = $this->data['id'];
        $updateInfo['name'] = $this->data['name'];
        $updateInfo['starttime'] = strtotime($this->data['starttime']);
        $updateInfo['endtime'] = strtotime($this->data['endtime']);
        $updateInfo['type'] = implode(',', $this->data['type']);

        if ($this->data['credit'] > 0 && $this->data['creditnum'] > 0) {
            $creditArray[$this->data['credit']] = $this->data['creditnum'];
        } else {
            $this->error('您填写的奖励设置不正确,请重新填写!');
        }
        $updateInfo['credit'] = serialize($creditArray);
        $this->data['addmode'] = (int)$this->data['addmode'];
        $this->data['addnum'] = (int)$this->data['addnum'];
        if ($this->data['addmode'] > 0 && $this->data['addnum'] >= 0) {
            $paramArray['addmode'] = (int)$this->data['addmode'];
            $paramArray['addmax'] = (int)$this->data['addmax'];
        } else {
            $this->error('您填写的奖励模式不正确,请重新填写!');
        }
        if (empty($this->data['get'])) {
            $this->error('分享规则中三个必须需要选择一个!');
        }
        if ($this->data['get']['topic']) {
            $paramArray['topic']['tid'] = $this->data['topic']['tid'];
            $paramArray['topic']['fid'] = $this->data['topic']['fid'];
        }
        if ($this->data['get']['portal']) {
            $paramArray['portal']['aid'] = $this->data['portal']['aid'];
        }
        if ($this->data['get']['app']) {
            $paramArray['app'] = true;
        }
        $updateInfo['param'] = serialize($paramArray);
        if (strlen($id) != 0) {
            $this->db->update('appbyme_share', $updateInfo, array('id' => $id));
        } else {
            $this->db->insert('appbyme_share', $updateInfo);
        }
    }

    /**
     * 获取分享记录
     */
    public function actionShareLog()
    {
        $id = $this->data['id'];
        (int)$page = isset($this->data['page']) ? $this->data['page'] : 1;
        $pageSize = 20;
        $str = ($page - 1) * $pageSize;
        $sql = 'SELECT * FROM %t WHERE activityid=%s ORDER BY id LIMIT %d,%d';
        $where = $id;
        $data['items'] = $this->db->queryAll($sql, array('appbyme_share_user', $where, $str, $pageSize));
        $count = $this->db->queryRow("SELECT count(id) AS total_items FROM %t where activityid=%s", array('appbyme_share_user', $where));
        $data['total_items'] = $count['total_items'];//共多少条数据
        $data['current'] = $page;//现在在第几页
        $data['total_pages'] = ceil($count['total_items'] / $pageSize);//计算共几页
        if ($page != 1) {
            $data['before'] = $page - 1;//上一页
        }
        if ($page != $data['total_pages']) {
            $data['next'] = $page + 1;//下一页
        }
        $data['limit'] = $pageSize;//每页展示数据条数
        $this->setData($data);
    }

    /**
     * 删除分享
     */
    public function actionShareDel()
    {
        $id = $this->data['id'];
        $this->db->delete('appbyme_share', array('id' => $id));
        $this->db->delete('appbyme_share_user', array('id' => $id));
    }

    /**
     * 设为默认
     */
    public function actionShareEditConfig()
    {
        $id = $this->data['id'];
        $shareActivityIdKey = array('ckey' => 'share_activityid', 'cvalue' => $id);
        $tempData = DB::fetch_first("SELECT * FROM " . DB::table('appbyme_config') . " WHERE ckey='share_activityid'");
        if (empty($tempData)) {
            DB::insert('appbyme_config', $shareActivityIdKey);
        } else {
            DB::update('appbyme_config', $shareActivityIdKey, array('ckey' => 'share_activityid'));
        }
    }

}